### ISSUE TITLE
Analog Sticks, can't find previous build

### ISSUE THREAD

**Issue by Kyraminol** [alexsharoff/pcsx2-online#13]
Lastest build broke Analog Sticks support, which is required in most games, and november build seems vanished from the web, can you please reupload that or fix analog?

**Comment by manuelx98** [comment]
You can download the November build http://www.mediafire.com/?762wyrkr9pzf46j

**Comment by ReluctantSniper** [comment]
The build before the broken analog sticks is still up, but its been decompiled 3 or 4 different fucking ways. I've sat here for an hour or 2 trying compile the code, but I don't understand even a quarter of what I'm doing. It's the author's code and all, kudos to him, but could he be a bigger prick? He states simply that he has disabled analog sticks, doesn't say how, doesn't give a good reason why, and doesn't leave a version up that actually works with 90% of games. Instead of playing some games from my childhood with my best friend, I'm stuck trying to compile code for my very first time. It's so frustrating! And the instructions he includes are clearly meant for someone with experience. I really wish he would just keep 2 versions up, but its been 4 years since hes been active. Ugh

**Comment by Kyraminol** [comment]
That's exactly my problem.
If you go to readme revisions you can clearly see old mediafire download but it's down for somefuckingreason. I mean, who doesn't use those sticks c'mon, for example ape escape it's ALL sticks'n'stuff. Me and a friend wanted to play Digimon world 4 but clearly the pg stands still because it moves by sticks. Frustrating is the only word I have for this situation.

**Comment by Xlaits** [comment]
Another person who's trying to play Digimon World 4 here, can't use sticks, can't connect period.
